#!/bin/bash

# 定义要卸载的文件夹路径
rm -f /root/vps666
DIR2="/usr/local/my_script"

# 卸载函数
uninstall() {
    echo "正在卸载..."

    # 检查并删除第一个文件夹
    if [ -d "$DIR1" ]; then
        rm -rf "$DIR1"
        echo "$DIR1 已成功删除。"
    else
        echo "$DIR1 不存在，无法删除。"
    fi

    # 检查并删除第二个文件夹
    if [ -d "$DIR2" ]; then
        rm -rf "$DIR2"
        echo "$DIR2 已成功删除。"
    else
        echo "$DIR2 不存在，无法删除。"
    fi

    echo "卸载完成。"
}

# 调用卸载函数
uninstall
